### ISSUE TITLE
readout protection

### ISSUE THREAD

**Issue by ospilos** [atc1441/ESP_CC_Flasher#2]
Dear Aaron!
It seems that you are some pretty skilled EE, so maybe you would be kind enough to share a piece of info with your not-so-gifted collegue:
Are you aware of any means to access and read & dump a CC1110/CC2510 flash when the read-out lock bits were set?
I only was able to read the flash partially after issuing the MASS_ERASE_FLASH() and then immediately powering the micro off - but the first flash page is to be always lost by this procedure.
Any help will be warmly gratitudified.
Cheers!
Tom

**Comment by redfast00** [comment]
> I only was able to read the flash partially after issuing the MASS_ERASE_FLASH() and then immediately powering the micro off - but the first flash page is to be always lost by this procedure.

This does not seem to work on my CC2510 (device id 8104): it wipes the entire flash contents, even when immediately powered off after issueing the command.

**Comment by redfast00** [comment]
@ospilos here's one way to bypass read-out protection: https://zeus.ugent.be/blog/22-23/reverse_engineering_epaper/
